services:

  postgresql_user:
    container_name: ms_pg_sql_user
    image: postgres:16.3
    environment:
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: qwe
      PGDATA: /var/lib/data/postgres/user
    volumes:
      - postgres:/var/lib/data/postgres/user
    ports:
      - "1001:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  postgresql_resource:
    container_name: ms_pg_sql_resource
    image: postgres:16.3
    environment:
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: qwe
      PGDATA: /var/lib/data/postgres/resource
    volumes:
      - postgres:/var/lib/data/postgres/resource
    ports:
      - "1002:5432"
    networks:
      - microservices-net
    restart: unless-stopped


networks:
  microservices-net:
    driver: bridge

volumes:
  postgres: